/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_MNaccueil (void)
{
  GtkWidget *MNaccueil;
  GtkWidget *fixed2;
  GtkWidget *MNtreeview1;
  GtkWidget *MN_bienvenue;
  GtkWidget *MN_selection;
  GtkWidget *MN_ajouteracc;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *MN_modifieracc;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *MN_supprimeracc;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *MN_rechercheracc;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label60;
  GtkWidget *MN_buttontache2;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label103;
  GtkWidget *MN_afficheraccu;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label100;
  GtkWidget *MN_liste;
  GtkWidget *MN_deconnexion;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label61;

  MNaccueil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNaccueil), _("Accueil"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (MNaccueil), fixed2);

  MNtreeview1 = gtk_tree_view_new ();
  gtk_widget_show (MNtreeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), MNtreeview1, 16, 104);
  gtk_widget_set_size_request (MNtreeview1, 1432, 536);

  MN_bienvenue = gtk_label_new (_("Bienvenue \303\240 votre espace administrateur"));
  gtk_widget_show (MN_bienvenue);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_bienvenue, 464, 8);
  gtk_widget_set_size_request (MN_bienvenue, 649, 32);

  MN_selection = gtk_label_new ("");
  gtk_widget_show (MN_selection);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_selection, 568, 64);
  gtk_widget_set_size_request (MN_selection, 456, 48);

  MN_ajouteracc = gtk_button_new ();
  gtk_widget_show (MN_ajouteracc);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_ajouteracc, 40, 656);
  gtk_widget_set_size_request (MN_ajouteracc, 160, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (MN_ajouteracc), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  MN_modifieracc = gtk_button_new ();
  gtk_widget_show (MN_modifieracc);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_modifieracc, 248, 656);
  gtk_widget_set_size_request (MN_modifieracc, 168, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (MN_modifieracc), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  MN_supprimeracc = gtk_button_new ();
  gtk_widget_show (MN_supprimeracc);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_supprimeracc, 472, 656);
  gtk_widget_set_size_request (MN_supprimeracc, 176, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (MN_supprimeracc), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  MN_rechercheracc = gtk_button_new ();
  gtk_widget_show (MN_rechercheracc);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_rechercheracc, 720, 656);
  gtk_widget_set_size_request (MN_rechercheracc, 168, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (MN_rechercheracc), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox19), label60, FALSE, FALSE, 0);

  MN_buttontache2 = gtk_button_new ();
  gtk_widget_show (MN_buttontache2);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_buttontache2, 992, 656);
  gtk_widget_set_size_request (MN_buttontache2, 224, 40);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (MN_buttontache2), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Etage contenant le panne"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox26), label103, FALSE, FALSE, 0);

  MN_afficheraccu = gtk_button_new ();
  gtk_widget_show (MN_afficheraccu);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_afficheraccu, 1264, 656);
  gtk_widget_set_size_request (MN_afficheraccu, 176, 40);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (MN_afficheraccu), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox24), label100, FALSE, FALSE, 0);

  MN_liste = gtk_label_new (_("Voici votre liste des utilisateurs:"));
  gtk_widget_show (MN_liste);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_liste, 0, 56);
  gtk_widget_set_size_request (MN_liste, 256, 56);

  MN_deconnexion = gtk_button_new ();
  gtk_widget_show (MN_deconnexion);
  gtk_fixed_put (GTK_FIXED (fixed2), MN_deconnexion, 8, 8);
  gtk_widget_set_size_request (MN_deconnexion, 136, 45);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (MN_deconnexion), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox20), label61, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MNtreeview1, "row_activated",
                    G_CALLBACK (on_MNtreeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) MN_ajouteracc, "clicked",
                    G_CALLBACK (on_MNajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_modifieracc, "clicked",
                    G_CALLBACK (on_MNmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_supprimeracc, "clicked",
                    G_CALLBACK (on_MNsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_rechercheracc, "clicked",
                    G_CALLBACK (on_MN_rechercheracc_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_buttontache2, "clicked",
                    G_CALLBACK (on_MN_buttontache2_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_afficheraccu, "clicked",
                    G_CALLBACK (on_MN_afficheraccu_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_deconnexion, "clicked",
                    G_CALLBACK (on_MN_deconnexion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNaccueil, MNaccueil, "MNaccueil");
  GLADE_HOOKUP_OBJECT (MNaccueil, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (MNaccueil, MNtreeview1, "MNtreeview1");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_bienvenue, "MN_bienvenue");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_selection, "MN_selection");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_ajouteracc, "MN_ajouteracc");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (MNaccueil, image3, "image3");
  GLADE_HOOKUP_OBJECT (MNaccueil, label4, "label4");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_modifieracc, "MN_modifieracc");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (MNaccueil, image4, "image4");
  GLADE_HOOKUP_OBJECT (MNaccueil, label5, "label5");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_supprimeracc, "MN_supprimeracc");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (MNaccueil, image5, "image5");
  GLADE_HOOKUP_OBJECT (MNaccueil, label6, "label6");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_rechercheracc, "MN_rechercheracc");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (MNaccueil, image19, "image19");
  GLADE_HOOKUP_OBJECT (MNaccueil, label60, "label60");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_buttontache2, "MN_buttontache2");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (MNaccueil, image26, "image26");
  GLADE_HOOKUP_OBJECT (MNaccueil, label103, "label103");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_afficheraccu, "MN_afficheraccu");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (MNaccueil, image24, "image24");
  GLADE_HOOKUP_OBJECT (MNaccueil, label100, "label100");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_liste, "MN_liste");
  GLADE_HOOKUP_OBJECT (MNaccueil, MN_deconnexion, "MN_deconnexion");
  GLADE_HOOKUP_OBJECT (MNaccueil, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (MNaccueil, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (MNaccueil, image20, "image20");
  GLADE_HOOKUP_OBJECT (MNaccueil, label61, "label61");

  return MNaccueil;
}

GtkWidget*
create_MNajout (void)
{
  GtkWidget *MNajout;
  GtkWidget *fixed3;
  GtkWidget *MNentry_nom;
  GtkWidget *MNentry_prenom;
  GtkWidget *MN_entrycin;
  GtkObject *MN_spinbuttonjour_adj;
  GtkWidget *MN_spinbuttonjour;
  GtkObject *MN_spinbuttonmois_adj;
  GtkWidget *MN_spinbuttonmois;
  GtkObject *MN_spinbuttonannee_adj;
  GtkWidget *MN_spinbuttonannee;
  GtkWidget *MNentry_id;
  GtkWidget *MNentry_pass;
  GtkWidget *MN_entryadresse;
  GtkWidget *MN_entry;
  GtkWidget *MN_entrytel;
  GtkWidget *MN_insription;
  GtkWidget *MN_nom;
  GtkWidget *MN_prenom;
  GtkWidget *MN_sexe;
  GtkWidget *MNradio_femelle;
  GSList *MNradio_femelle_group = NULL;
  GtkWidget *MNradio_male;
  GtkWidget *MN_cin;
  GtkWidget *MN_datenais;
  GtkWidget *MN_jour;
  GtkWidget *MN_mois;
  GtkWidget *MN_annee;
  GtkWidget *MN_verifnom;
  GtkWidget *MN_verifprenom;
  GtkWidget *MN_verifcin;
  GtkWidget *MN_pass;
  GtkWidget *MN_id;
  GtkWidget *MN_role;
  GtkWidget *MN_comboboxrole;
  GtkWidget *MN_verifident;
  GtkWidget *MN_verifpassword;
  GtkWidget *MN_verifrole;
  GtkWidget *MN_adresse;
  GtkWidget *MN_mail;
  GtkWidget *MN_verifadresse;
  GtkWidget *MN_verifmail;
  GtkWidget *MN_tel;
  GtkWidget *MN_retourajout;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label65;
  GtkWidget *MN_veriftel;
  GtkWidget *MN_validajoutt;
  GtkWidget *MN_messageajout;
  GtkWidget *MN_validerajout;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label28;

  MNajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNajout), _("Ajout utilisateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (MNajout), fixed3);

  MNentry_nom = gtk_entry_new ();
  gtk_widget_show (MNentry_nom);
  gtk_fixed_put (GTK_FIXED (fixed3), MNentry_nom, 120, 48);
  gtk_widget_set_size_request (MNentry_nom, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (MNentry_nom), 8226);

  MNentry_prenom = gtk_entry_new ();
  gtk_widget_show (MNentry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), MNentry_prenom, 448, 40);
  gtk_widget_set_size_request (MNentry_prenom, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (MNentry_prenom), 8226);

  MN_entrycin = gtk_entry_new ();
  gtk_widget_show (MN_entrycin);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_entrycin, 112, 160);
  gtk_widget_set_size_request (MN_entrycin, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entrycin), 8226);

  MN_spinbuttonjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  MN_spinbuttonjour = gtk_spin_button_new (GTK_ADJUSTMENT (MN_spinbuttonjour_adj), 1, 0);
  gtk_widget_show (MN_spinbuttonjour);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_spinbuttonjour, 136, 264);
  gtk_widget_set_size_request (MN_spinbuttonjour, 60, 27);

  MN_spinbuttonmois_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  MN_spinbuttonmois = gtk_spin_button_new (GTK_ADJUSTMENT (MN_spinbuttonmois_adj), 1, 0);
  gtk_widget_show (MN_spinbuttonmois);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_spinbuttonmois, 312, 264);
  gtk_widget_set_size_request (MN_spinbuttonmois, 60, 27);

  MN_spinbuttonannee_adj = gtk_adjustment_new (1, 1950, 2022, 1, 10, 10);
  MN_spinbuttonannee = gtk_spin_button_new (GTK_ADJUSTMENT (MN_spinbuttonannee_adj), 1, 0);
  gtk_widget_show (MN_spinbuttonannee);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_spinbuttonannee, 480, 264);
  gtk_widget_set_size_request (MN_spinbuttonannee, 60, 27);

  MNentry_id = gtk_entry_new ();
  gtk_widget_show (MNentry_id);
  gtk_fixed_put (GTK_FIXED (fixed3), MNentry_id, 144, 312);
  gtk_widget_set_size_request (MNentry_id, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MNentry_id), 8226);

  MNentry_pass = gtk_entry_new ();
  gtk_widget_show (MNentry_pass);
  gtk_fixed_put (GTK_FIXED (fixed3), MNentry_pass, 144, 368);
  gtk_widget_set_size_request (MNentry_pass, 184, 32);
  gtk_entry_set_visibility (GTK_ENTRY (MNentry_pass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (MNentry_pass), 8226);

  MN_entryadresse = gtk_entry_new ();
  gtk_widget_show (MN_entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_entryadresse, 136, 496);
  gtk_widget_set_size_request (MN_entryadresse, 712, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entryadresse), 8226);

  MN_entry = gtk_entry_new ();
  gtk_widget_show (MN_entry);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_entry, 136, 576);
  gtk_widget_set_size_request (MN_entry, 712, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entry), 8226);

  MN_entrytel = gtk_entry_new ();
  gtk_widget_show (MN_entrytel);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_entrytel, 176, 664);
  gtk_widget_set_size_request (MN_entrytel, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entrytel), 8226);

  MN_insription = gtk_label_new (_("Veuillez remplir ce formulaire:"));
  gtk_widget_show (MN_insription);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_insription, 0, 8);
  gtk_widget_set_size_request (MN_insription, 312, 40);

  MN_nom = gtk_label_new (_("Nom:"));
  gtk_widget_show (MN_nom);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_nom, 40, 48);
  gtk_widget_set_size_request (MN_nom, 81, 33);

  MN_prenom = gtk_label_new (_("Prenom:"));
  gtk_widget_show (MN_prenom);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_prenom, 360, 48);
  gtk_widget_set_size_request (MN_prenom, 81, 33);

  MN_sexe = gtk_label_new (_("Sexe:"));
  gtk_widget_show (MN_sexe);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_sexe, 40, 120);
  gtk_widget_set_size_request (MN_sexe, 81, 33);

  MNradio_femelle = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (MNradio_femelle);
  gtk_fixed_put (GTK_FIXED (fixed3), MNradio_femelle, 120, 128);
  gtk_widget_set_size_request (MNradio_femelle, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MNradio_femelle), MNradio_femelle_group);
  MNradio_femelle_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MNradio_femelle));

  MNradio_male = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (MNradio_male);
  gtk_fixed_put (GTK_FIXED (fixed3), MNradio_male, 264, 128);
  gtk_widget_set_size_request (MNradio_male, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MNradio_male), MNradio_femelle_group);
  MNradio_femelle_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MNradio_male));

  MN_cin = gtk_label_new (_("CIN:"));
  gtk_widget_show (MN_cin);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_cin, 16, 160);
  gtk_widget_set_size_request (MN_cin, 121, 33);

  MN_datenais = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (MN_datenais);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_datenais, 24, 208);
  gtk_widget_set_size_request (MN_datenais, 200, 40);

  MN_jour = gtk_label_new (_("Jour:"));
  gtk_widget_show (MN_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_jour, 24, 264);
  gtk_widget_set_size_request (MN_jour, 128, 24);

  MN_mois = gtk_label_new (_("Mois:"));
  gtk_widget_show (MN_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_mois, 232, 264);
  gtk_widget_set_size_request (MN_mois, 88, 25);

  MN_annee = gtk_label_new (_("Annee:"));
  gtk_widget_show (MN_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_annee, 400, 264);
  gtk_widget_set_size_request (MN_annee, 88, 25);

  MN_verifnom = gtk_label_new ("");
  gtk_widget_show (MN_verifnom);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifnom, 104, 88);
  gtk_widget_set_size_request (MN_verifnom, 256, 32);

  MN_verifprenom = gtk_label_new ("");
  gtk_widget_show (MN_verifprenom);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifprenom, 504, 96);
  gtk_widget_set_size_request (MN_verifprenom, 264, 32);

  MN_verifcin = gtk_label_new ("");
  gtk_widget_show (MN_verifcin);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifcin, 408, 160);
  gtk_widget_set_size_request (MN_verifcin, 320, 40);

  MN_pass = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (MN_pass);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_pass, 8, 368);
  gtk_widget_set_size_request (MN_pass, 136, 32);

  MN_id = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (MN_id);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_id, 16, 312);
  gtk_widget_set_size_request (MN_id, 136, 32);

  MN_role = gtk_label_new (_("Role:"));
  gtk_widget_show (MN_role);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_role, 48, 408);
  gtk_widget_set_size_request (MN_role, 121, 56);
  gtk_misc_set_alignment (GTK_MISC (MN_role), 0.5, 0.49);

  MN_comboboxrole = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MN_comboboxrole);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_comboboxrole, 144, 424);
  gtk_widget_set_size_request (MN_comboboxrole, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Agent_de_foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Agent_de_reclamation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Nutrisionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Etudiant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Agent_de_club"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Agent_de_stock "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxrole), _("Administrateur"));

  MN_verifident = gtk_label_new ("");
  gtk_widget_show (MN_verifident);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifident, 344, 312);
  gtk_widget_set_size_request (MN_verifident, 360, 32);

  MN_verifpassword = gtk_label_new ("");
  gtk_widget_show (MN_verifpassword);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifpassword, 344, 360);
  gtk_widget_set_size_request (MN_verifpassword, 536, 40);

  MN_verifrole = gtk_label_new ("");
  gtk_widget_show (MN_verifrole);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifrole, 368, 416);
  gtk_widget_set_size_request (MN_verifrole, 336, 40);

  MN_adresse = gtk_label_new (_("Adresse:"));
  gtk_widget_show (MN_adresse);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_adresse, 40, 488);
  gtk_widget_set_size_request (MN_adresse, 113, 41);

  MN_mail = gtk_label_new (_("Adresse mail:"));
  gtk_widget_show (MN_mail);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_mail, 8, 576);
  gtk_widget_set_size_request (MN_mail, 144, 33);

  MN_verifadresse = gtk_label_new ("");
  gtk_widget_show (MN_verifadresse);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifadresse, 136, 536);
  gtk_widget_set_size_request (MN_verifadresse, 360, 32);

  MN_verifmail = gtk_label_new ("");
  gtk_widget_show (MN_verifmail);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_verifmail, 136, 616);
  gtk_widget_set_size_request (MN_verifmail, 376, 32);

  MN_tel = gtk_label_new (_("Numero de telephone:"));
  gtk_widget_show (MN_tel);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_tel, 0, 656);
  gtk_widget_set_size_request (MN_tel, 185, 41);

  MN_retourajout = gtk_button_new ();
  gtk_widget_show (MN_retourajout);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_retourajout, 8, 760);
  gtk_widget_set_size_request (MN_retourajout, 176, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (MN_retourajout), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox23), label65, FALSE, FALSE, 0);

  MN_veriftel = gtk_label_new ("");
  gtk_widget_show (MN_veriftel);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_veriftel, 392, 664);
  gtk_widget_set_size_request (MN_veriftel, 344, 32);

  MN_validajoutt = gtk_label_new ("");
  gtk_widget_show (MN_validajoutt);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_validajoutt, 272, 752);
  gtk_widget_set_size_request (MN_validajoutt, 304, 41);

  MN_messageajout = gtk_label_new ("");
  gtk_widget_show (MN_messageajout);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_messageajout, 32, 704);
  gtk_widget_set_size_request (MN_messageajout, 800, 40);

  MN_validerajout = gtk_button_new ();
  gtk_widget_show (MN_validerajout);
  gtk_fixed_put (GTK_FIXED (fixed3), MN_validerajout, 696, 760);
  gtk_widget_set_size_request (MN_validerajout, 176, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (MN_validerajout), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox7), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MNradio_femelle, "toggled",
                    G_CALLBACK (on_MNradio_femelle_toggled),
                    NULL);
  g_signal_connect ((gpointer) MNradio_male, "toggled",
                    G_CALLBACK (on_MNradio_male_toggled),
                    NULL);
  g_signal_connect ((gpointer) MN_retourajout, "clicked",
                    G_CALLBACK (on_MN_retourajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_validerajout, "clicked",
                    G_CALLBACK (on_MN_validerajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNajout, MNajout, "MNajout");
  GLADE_HOOKUP_OBJECT (MNajout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (MNajout, MNentry_nom, "MNentry_nom");
  GLADE_HOOKUP_OBJECT (MNajout, MNentry_prenom, "MNentry_prenom");
  GLADE_HOOKUP_OBJECT (MNajout, MN_entrycin, "MN_entrycin");
  GLADE_HOOKUP_OBJECT (MNajout, MN_spinbuttonjour, "MN_spinbuttonjour");
  GLADE_HOOKUP_OBJECT (MNajout, MN_spinbuttonmois, "MN_spinbuttonmois");
  GLADE_HOOKUP_OBJECT (MNajout, MN_spinbuttonannee, "MN_spinbuttonannee");
  GLADE_HOOKUP_OBJECT (MNajout, MNentry_id, "MNentry_id");
  GLADE_HOOKUP_OBJECT (MNajout, MNentry_pass, "MNentry_pass");
  GLADE_HOOKUP_OBJECT (MNajout, MN_entryadresse, "MN_entryadresse");
  GLADE_HOOKUP_OBJECT (MNajout, MN_entry, "MN_entry");
  GLADE_HOOKUP_OBJECT (MNajout, MN_entrytel, "MN_entrytel");
  GLADE_HOOKUP_OBJECT (MNajout, MN_insription, "MN_insription");
  GLADE_HOOKUP_OBJECT (MNajout, MN_nom, "MN_nom");
  GLADE_HOOKUP_OBJECT (MNajout, MN_prenom, "MN_prenom");
  GLADE_HOOKUP_OBJECT (MNajout, MN_sexe, "MN_sexe");
  GLADE_HOOKUP_OBJECT (MNajout, MNradio_femelle, "MNradio_femelle");
  GLADE_HOOKUP_OBJECT (MNajout, MNradio_male, "MNradio_male");
  GLADE_HOOKUP_OBJECT (MNajout, MN_cin, "MN_cin");
  GLADE_HOOKUP_OBJECT (MNajout, MN_datenais, "MN_datenais");
  GLADE_HOOKUP_OBJECT (MNajout, MN_jour, "MN_jour");
  GLADE_HOOKUP_OBJECT (MNajout, MN_mois, "MN_mois");
  GLADE_HOOKUP_OBJECT (MNajout, MN_annee, "MN_annee");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifnom, "MN_verifnom");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifprenom, "MN_verifprenom");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifcin, "MN_verifcin");
  GLADE_HOOKUP_OBJECT (MNajout, MN_pass, "MN_pass");
  GLADE_HOOKUP_OBJECT (MNajout, MN_id, "MN_id");
  GLADE_HOOKUP_OBJECT (MNajout, MN_role, "MN_role");
  GLADE_HOOKUP_OBJECT (MNajout, MN_comboboxrole, "MN_comboboxrole");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifident, "MN_verifident");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifpassword, "MN_verifpassword");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifrole, "MN_verifrole");
  GLADE_HOOKUP_OBJECT (MNajout, MN_adresse, "MN_adresse");
  GLADE_HOOKUP_OBJECT (MNajout, MN_mail, "MN_mail");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifadresse, "MN_verifadresse");
  GLADE_HOOKUP_OBJECT (MNajout, MN_verifmail, "MN_verifmail");
  GLADE_HOOKUP_OBJECT (MNajout, MN_tel, "MN_tel");
  GLADE_HOOKUP_OBJECT (MNajout, MN_retourajout, "MN_retourajout");
  GLADE_HOOKUP_OBJECT (MNajout, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (MNajout, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (MNajout, image23, "image23");
  GLADE_HOOKUP_OBJECT (MNajout, label65, "label65");
  GLADE_HOOKUP_OBJECT (MNajout, MN_veriftel, "MN_veriftel");
  GLADE_HOOKUP_OBJECT (MNajout, MN_validajoutt, "MN_validajoutt");
  GLADE_HOOKUP_OBJECT (MNajout, MN_messageajout, "MN_messageajout");
  GLADE_HOOKUP_OBJECT (MNajout, MN_validerajout, "MN_validerajout");
  GLADE_HOOKUP_OBJECT (MNajout, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (MNajout, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (MNajout, image7, "image7");
  GLADE_HOOKUP_OBJECT (MNajout, label28, "label28");

  return MNajout;
}

GtkWidget*
create_MNmodif (void)
{
  GtkWidget *MNmodif;
  GtkWidget *fixed4;
  GtkWidget *MN_modifentrynom;
  GtkWidget *MN_modifentryprenom;
  GtkWidget *MN_entrymodifcin;
  GtkObject *MN_modifjourspin_adj;
  GtkWidget *MN_modifjourspin;
  GtkObject *MN_modifmoisspin_adj;
  GtkWidget *MN_modifmoisspin;
  GtkObject *MN_modifanneespin_adj;
  GtkWidget *MN_modifanneespin;
  GtkWidget *MN_modifentrypass;
  GtkWidget *MN_adresseentrymodif;
  GtkWidget *MN_mailmodifentry;
  GtkWidget *MN_numtelmodifentry;
  GtkWidget *MN_entrymodifid;
  GtkWidget *Mn_modifsexe;
  GtkWidget *MN_infmodif;
  GtkWidget *MN_nommodif;
  GtkWidget *MN_modifprenom;
  GtkWidget *MN_radiomalemodif;
  GSList *MN_radiomalemodif_group = NULL;
  GtkWidget *MN_radiofemellemodif;
  GtkWidget *MN_verifmodifnom;
  GtkWidget *MN_CINmodif;
  GtkWidget *MN_datenaismodif;
  GtkWidget *MN_modifjour;
  GtkWidget *MN_modifmois;
  GtkWidget *MN_modifannee;
  GtkWidget *MN_passmodif;
  GtkWidget *MN_modifid;
  GtkWidget *MN_modifrole;
  GtkWidget *MN_comboboxmodif;
  GtkWidget *MN_adressemodif;
  GtkWidget *MN_mailmodif;
  GtkWidget *MN_verifmodifadresse;
  GtkWidget *MN_verifmodifmail;
  GtkWidget *MN_numtelmodif;
  GtkWidget *MN_retourmodifier;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label104;
  GtkWidget *MN_verifmodifprenom;
  GtkWidget *MN_verifmodifcin;
  GtkWidget *MN_verifmodifpass;
  GtkWidget *MN_validermodif;
  GtkWidget *_;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label42;
  GtkWidget *MN_verifmodifnumero;
  GtkWidget *MN_reumodif;

  MNmodif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNmodif), _("modifier utilisateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (MNmodif), fixed4);

  MN_modifentrynom = gtk_entry_new ();
  gtk_widget_show (MN_modifentrynom);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifentrynom, 120, 48);
  gtk_widget_set_size_request (MN_modifentrynom, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_modifentrynom), 8226);

  MN_modifentryprenom = gtk_entry_new ();
  gtk_widget_show (MN_modifentryprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifentryprenom, 448, 48);
  gtk_widget_set_size_request (MN_modifentryprenom, 224, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_modifentryprenom), 8226);

  MN_entrymodifcin = gtk_entry_new ();
  gtk_widget_show (MN_entrymodifcin);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_entrymodifcin, 128, 184);
  gtk_widget_set_size_request (MN_entrymodifcin, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entrymodifcin), 8226);

  MN_modifjourspin_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  MN_modifjourspin = gtk_spin_button_new (GTK_ADJUSTMENT (MN_modifjourspin_adj), 1, 0);
  gtk_widget_show (MN_modifjourspin);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifjourspin, 176, 280);
  gtk_widget_set_size_request (MN_modifjourspin, 64, 27);

  MN_modifmoisspin_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  MN_modifmoisspin = gtk_spin_button_new (GTK_ADJUSTMENT (MN_modifmoisspin_adj), 1, 0);
  gtk_widget_show (MN_modifmoisspin);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifmoisspin, 360, 280);
  gtk_widget_set_size_request (MN_modifmoisspin, 60, 27);

  MN_modifanneespin_adj = gtk_adjustment_new (1950, 1950, 2022, 1, 10, 10);
  MN_modifanneespin = gtk_spin_button_new (GTK_ADJUSTMENT (MN_modifanneespin_adj), 1, 0);
  gtk_widget_show (MN_modifanneespin);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifanneespin, 536, 280);
  gtk_widget_set_size_request (MN_modifanneespin, 64, 27);

  MN_modifentrypass = gtk_entry_new ();
  gtk_widget_show (MN_modifentrypass);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifentrypass, 160, 384);
  gtk_widget_set_size_request (MN_modifentrypass, 184, 32);
  gtk_entry_set_visibility (GTK_ENTRY (MN_modifentrypass), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_modifentrypass), 8226);

  MN_adresseentrymodif = gtk_entry_new ();
  gtk_widget_show (MN_adresseentrymodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_adresseentrymodif, 152, 496);
  gtk_widget_set_size_request (MN_adresseentrymodif, 432, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_adresseentrymodif), 8226);

  MN_mailmodifentry = gtk_entry_new ();
  gtk_widget_show (MN_mailmodifentry);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_mailmodifentry, 144, 576);
  gtk_widget_set_size_request (MN_mailmodifentry, 632, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_mailmodifentry), 8226);

  MN_numtelmodifentry = gtk_entry_new ();
  gtk_widget_show (MN_numtelmodifentry);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_numtelmodifentry, 192, 656);
  gtk_widget_set_size_request (MN_numtelmodifentry, 240, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_numtelmodifentry), 8226);

  MN_entrymodifid = gtk_entry_new ();
  gtk_widget_show (MN_entrymodifid);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_entrymodifid, 160, 336);
  gtk_widget_set_size_request (MN_entrymodifid, 184, 32);
  gtk_editable_set_editable (GTK_EDITABLE (MN_entrymodifid), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entrymodifid), 8226);

  Mn_modifsexe = gtk_label_new (_("Sexe:"));
  gtk_widget_show (Mn_modifsexe);
  gtk_fixed_put (GTK_FIXED (fixed4), Mn_modifsexe, 40, 136);
  gtk_widget_set_size_request (Mn_modifsexe, 81, 33);

  MN_infmodif = gtk_label_new (_("veuillez saisir les champs \303\240 modifier:"));
  gtk_widget_show (MN_infmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_infmodif, 0, 8);
  gtk_widget_set_size_request (MN_infmodif, 296, 40);

  MN_nommodif = gtk_label_new (_("Nom:"));
  gtk_widget_show (MN_nommodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_nommodif, 40, 48);
  gtk_widget_set_size_request (MN_nommodif, 81, 33);

  MN_modifprenom = gtk_label_new (_("Prenom:"));
  gtk_widget_show (MN_modifprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifprenom, 368, 48);
  gtk_widget_set_size_request (MN_modifprenom, 81, 33);

  MN_radiomalemodif = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (MN_radiomalemodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_radiomalemodif, 288, 144);
  gtk_widget_set_size_request (MN_radiomalemodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MN_radiomalemodif), MN_radiomalemodif_group);
  MN_radiomalemodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MN_radiomalemodif));

  MN_radiofemellemodif = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (MN_radiofemellemodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_radiofemellemodif, 144, 144);
  gtk_widget_set_size_request (MN_radiofemellemodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (MN_radiofemellemodif), MN_radiomalemodif_group);
  MN_radiomalemodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (MN_radiofemellemodif));

  MN_verifmodifnom = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifnom);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifnom, 72, 88);
  gtk_widget_set_size_request (MN_verifmodifnom, 312, 32);

  MN_CINmodif = gtk_label_new (_("CIN:"));
  gtk_widget_show (MN_CINmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_CINmodif, 32, 184);
  gtk_widget_set_size_request (MN_CINmodif, 121, 33);

  MN_datenaismodif = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (MN_datenaismodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_datenaismodif, 8, 232);
  gtk_widget_set_size_request (MN_datenaismodif, 200, 40);

  MN_modifjour = gtk_label_new (_("Jour:"));
  gtk_widget_show (MN_modifjour);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifjour, 96, 280);
  gtk_widget_set_size_request (MN_modifjour, 80, 24);

  MN_modifmois = gtk_label_new (_("Mois:"));
  gtk_widget_show (MN_modifmois);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifmois, 280, 280);
  gtk_widget_set_size_request (MN_modifmois, 88, 25);

  MN_modifannee = gtk_label_new (_("Annee:"));
  gtk_widget_show (MN_modifannee);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifannee, 456, 280);
  gtk_widget_set_size_request (MN_modifannee, 88, 25);

  MN_passmodif = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (MN_passmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_passmodif, 32, 384);
  gtk_widget_set_size_request (MN_passmodif, 136, 32);

  MN_modifid = gtk_label_new (_("identifiant:"));
  gtk_widget_show (MN_modifid);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifid, 64, 336);
  gtk_widget_set_size_request (MN_modifid, 96, 24);

  MN_modifrole = gtk_label_new (_("Role:"));
  gtk_widget_show (MN_modifrole);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_modifrole, 64, 432);
  gtk_widget_set_size_request (MN_modifrole, 121, 56);
  gtk_misc_set_alignment (GTK_MISC (MN_modifrole), 0.5, 0.49);

  MN_comboboxmodif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (MN_comboboxmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_comboboxmodif, 160, 448);
  gtk_widget_set_size_request (MN_comboboxmodif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Agent_de _foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Agent_de_reclamation"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Nutrisionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Etudiant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Agent_de_club"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Agent_de_stock "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (MN_comboboxmodif), _("Administrateur"));

  MN_adressemodif = gtk_label_new (_("Adresse:"));
  gtk_widget_show (MN_adressemodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_adressemodif, 56, 488);
  gtk_widget_set_size_request (MN_adressemodif, 113, 41);

  MN_mailmodif = gtk_label_new (_("Adresse mail:"));
  gtk_widget_show (MN_mailmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_mailmodif, 40, 576);
  gtk_widget_set_size_request (MN_mailmodif, 104, 41);

  MN_verifmodifadresse = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifadresse);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifadresse, 248, 536);
  gtk_widget_set_size_request (MN_verifmodifadresse, 472, 32);

  MN_verifmodifmail = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifmail);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifmail, 224, 616);
  gtk_widget_set_size_request (MN_verifmodifmail, 400, 32);

  MN_numtelmodif = gtk_label_new (_("Numero de telephone:"));
  gtk_widget_show (MN_numtelmodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_numtelmodif, 16, 656);
  gtk_widget_set_size_request (MN_numtelmodif, 185, 41);

  MN_retourmodifier = gtk_button_new ();
  gtk_widget_show (MN_retourmodifier);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_retourmodifier, 16, 712);
  gtk_widget_set_size_request (MN_retourmodifier, 168, 40);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (MN_retourmodifier), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox27), label104, FALSE, FALSE, 0);

  MN_verifmodifprenom = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifprenom, 552, 96);
  gtk_widget_set_size_request (MN_verifmodifprenom, 264, 32);

  MN_verifmodifcin = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifcin);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifcin, 408, 184);
  gtk_widget_set_size_request (MN_verifmodifcin, 328, 32);

  MN_verifmodifpass = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifpass);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifpass, 360, 384);
  gtk_widget_set_size_request (MN_verifmodifpass, 504, 40);

  MN_validermodif = gtk_button_new ();
  gtk_widget_show (MN_validermodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_validermodif, 712, 704);
  gtk_widget_set_size_request (MN_validermodif, 168, 40);

  _ = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (_);
  gtk_container_add (GTK_CONTAINER (MN_validermodif), _);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (_), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox10), label42, FALSE, FALSE, 0);

  MN_verifmodifnumero = gtk_label_new ("");
  gtk_widget_show (MN_verifmodifnumero);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_verifmodifnumero, 448, 656);
  gtk_widget_set_size_request (MN_verifmodifnumero, 344, 40);

  MN_reumodif = gtk_label_new ("");
  gtk_widget_show (MN_reumodif);
  gtk_fixed_put (GTK_FIXED (fixed4), MN_reumodif, 264, 712);
  gtk_widget_set_size_request (MN_reumodif, 376, 48);

  g_signal_connect ((gpointer) MN_radiomalemodif, "toggled",
                    G_CALLBACK (on_MN_radiomalemodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) MN_radiofemellemodif, "toggled",
                    G_CALLBACK (on_MN_radiofemellemodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) MN_retourmodifier, "clicked",
                    G_CALLBACK (on_MN_retourmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_validermodif, "clicked",
                    G_CALLBACK (on_MN_validermodif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNmodif, MNmodif, "MNmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifentrynom, "MN_modifentrynom");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifentryprenom, "MN_modifentryprenom");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_entrymodifcin, "MN_entrymodifcin");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifjourspin, "MN_modifjourspin");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifmoisspin, "MN_modifmoisspin");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifanneespin, "MN_modifanneespin");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifentrypass, "MN_modifentrypass");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_adresseentrymodif, "MN_adresseentrymodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_mailmodifentry, "MN_mailmodifentry");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_numtelmodifentry, "MN_numtelmodifentry");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_entrymodifid, "MN_entrymodifid");
  GLADE_HOOKUP_OBJECT (MNmodif, Mn_modifsexe, "Mn_modifsexe");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_infmodif, "MN_infmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_nommodif, "MN_nommodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifprenom, "MN_modifprenom");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_radiomalemodif, "MN_radiomalemodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_radiofemellemodif, "MN_radiofemellemodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifnom, "MN_verifmodifnom");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_CINmodif, "MN_CINmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_datenaismodif, "MN_datenaismodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifjour, "MN_modifjour");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifmois, "MN_modifmois");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifannee, "MN_modifannee");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_passmodif, "MN_passmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifid, "MN_modifid");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_modifrole, "MN_modifrole");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_comboboxmodif, "MN_comboboxmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_adressemodif, "MN_adressemodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_mailmodif, "MN_mailmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifadresse, "MN_verifmodifadresse");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifmail, "MN_verifmodifmail");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_numtelmodif, "MN_numtelmodif");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_retourmodifier, "MN_retourmodifier");
  GLADE_HOOKUP_OBJECT (MNmodif, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (MNmodif, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (MNmodif, image27, "image27");
  GLADE_HOOKUP_OBJECT (MNmodif, label104, "label104");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifprenom, "MN_verifmodifprenom");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifcin, "MN_verifmodifcin");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifpass, "MN_verifmodifpass");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_validermodif, "MN_validermodif");
  GLADE_HOOKUP_OBJECT (MNmodif, _, "_");
  GLADE_HOOKUP_OBJECT (MNmodif, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (MNmodif, image10, "image10");
  GLADE_HOOKUP_OBJECT (MNmodif, label42, "label42");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_verifmodifnumero, "MN_verifmodifnumero");
  GLADE_HOOKUP_OBJECT (MNmodif, MN_reumodif, "MN_reumodif");

  return MNmodif;
}

GtkWidget*
create_MNsupprime (void)
{
  GtkWidget *MNsupprime;
  GtkWidget *fixed5;
  GtkWidget *MN_idensuppentry;
  GtkWidget *MN_supprimer;
  GtkWidget *MN_suppconf;
  GtkWidget *MN_checkconfirm;
  GtkWidget *MN_buttonsupprimer;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label50;
  GtkWidget *MN_retoursupprimer;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label63;
  GtkWidget *MN_msgsupp;

  MNsupprime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNsupprime), _("supprime utilisateurs"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (MNsupprime), fixed5);

  MN_idensuppentry = gtk_entry_new ();
  gtk_widget_show (MN_idensuppentry);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_idensuppentry, 384, 8);
  gtk_widget_set_size_request (MN_idensuppentry, 224, 32);
  gtk_editable_set_editable (GTK_EDITABLE (MN_idensuppentry), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_idensuppentry), 8226);

  MN_supprimer = gtk_label_new (_("L'identifiant de l'utilisateur \303\240 supprimer est:"));
  gtk_widget_show (MN_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_supprimer, 8, 8);
  gtk_widget_set_size_request (MN_supprimer, 352, 40);

  MN_suppconf = gtk_label_new (_("Etes-vous sur de supprimer votre utilisateur ?"));
  gtk_widget_show (MN_suppconf);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_suppconf, 176, 96);
  gtk_widget_set_size_request (MN_suppconf, 392, 33);

  MN_checkconfirm = gtk_check_button_new_with_mnemonic (_("Oui"));
  gtk_widget_show (MN_checkconfirm);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_checkconfirm, 336, 136);
  gtk_widget_set_size_request (MN_checkconfirm, 56, 32);

  MN_buttonsupprimer = gtk_button_new ();
  gtk_widget_show (MN_buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_buttonsupprimer, 304, 184);
  gtk_widget_set_size_request (MN_buttonsupprimer, 120, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (MN_buttonsupprimer), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox13), label50, FALSE, FALSE, 0);

  MN_retoursupprimer = gtk_button_new ();
  gtk_widget_show (MN_retoursupprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_retoursupprimer, 24, 256);
  gtk_widget_set_size_request (MN_retoursupprimer, 112, 37);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (MN_retoursupprimer), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox21), label63, FALSE, FALSE, 0);

  MN_msgsupp = gtk_label_new ("");
  gtk_widget_show (MN_msgsupp);
  gtk_fixed_put (GTK_FIXED (fixed5), MN_msgsupp, 208, 56);
  gtk_widget_set_size_request (MN_msgsupp, 432, 33);
  gtk_misc_set_alignment (GTK_MISC (MN_msgsupp), 0.45, 0.5);


  g_signal_connect ((gpointer) MN_checkconfirm, "toggled",
                    G_CALLBACK (on_MN_checkconfirm_toggled),
                    NULL);
  g_signal_connect ((gpointer) MN_buttonsupprimer, "clicked",
                    G_CALLBACK (on_MN_buttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_retoursupprimer, "clicked",
                    G_CALLBACK (on_MN_retoursupprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNsupprime, MNsupprime, "MNsupprime");
  GLADE_HOOKUP_OBJECT (MNsupprime, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_idensuppentry, "MN_idensuppentry");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_supprimer, "MN_supprimer");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_suppconf, "MN_suppconf");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_checkconfirm, "MN_checkconfirm");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_buttonsupprimer, "MN_buttonsupprimer");
  GLADE_HOOKUP_OBJECT (MNsupprime, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (MNsupprime, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (MNsupprime, image13, "image13");
  GLADE_HOOKUP_OBJECT (MNsupprime, label50, "label50");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_retoursupprimer, "MN_retoursupprimer");
  GLADE_HOOKUP_OBJECT (MNsupprime, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (MNsupprime, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (MNsupprime, image21, "image21");
  GLADE_HOOKUP_OBJECT (MNsupprime, label63, "label63");
  GLADE_HOOKUP_OBJECT (MNsupprime, MN_msgsupp, "MN_msgsupp");

  return MNsupprime;
}

GtkWidget*
create_MNcherche (void)
{
  GtkWidget *MNcherche;
  GtkWidget *fixed7;
  GtkWidget *MN_entryidchercher;
  GtkWidget *MNtreeview2;
  GtkWidget *MN_verifchercher;
  GtkWidget *MN_chercherbutton;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label59;
  GtkWidget *MN_resultatcher;
  GtkWidget *MN_textrechercher;
  GtkWidget *MN_retourchercher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label58;

  MNcherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNcherche), _("Chercher utilisateur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (MNcherche), fixed7);

  MN_entryidchercher = gtk_entry_new ();
  gtk_widget_show (MN_entryidchercher);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_entryidchercher, 352, 24);
  gtk_widget_set_size_request (MN_entryidchercher, 216, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_entryidchercher), 8226);

  MNtreeview2 = gtk_tree_view_new ();
  gtk_widget_show (MNtreeview2);
  gtk_fixed_put (GTK_FIXED (fixed7), MNtreeview2, 16, 136);
  gtk_widget_set_size_request (MNtreeview2, 1176, 48);

  MN_verifchercher = gtk_label_new (_("Donnez l'identifiant de l'utilisateur \303\240 chercher :"));
  gtk_widget_show (MN_verifchercher);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_verifchercher, 8, 24);
  gtk_widget_set_size_request (MN_verifchercher, 344, 40);

  MN_chercherbutton = gtk_button_new ();
  gtk_widget_show (MN_chercherbutton);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_chercherbutton, 616, 16);
  gtk_widget_set_size_request (MN_chercherbutton, 176, 53);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (MN_chercherbutton), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox18), label59, FALSE, FALSE, 0);

  MN_resultatcher = gtk_label_new (_("Voici les informations de votre utilisateur \303\240 chercher:"));
  gtk_widget_show (MN_resultatcher);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_resultatcher, 0, 88);
  gtk_widget_set_size_request (MN_resultatcher, 400, 48);

  MN_textrechercher = gtk_label_new ("");
  gtk_widget_show (MN_textrechercher);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_textrechercher, 520, 80);
  gtk_widget_set_size_request (MN_textrechercher, 256, 32);

  MN_retourchercher = gtk_button_new ();
  gtk_widget_show (MN_retourchercher);
  gtk_fixed_put (GTK_FIXED (fixed7), MN_retourchercher, 16, 208);
  gtk_widget_set_size_request (MN_retourchercher, 112, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (MN_retourchercher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox17), label58, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MNtreeview2, "row_activated",
                    G_CALLBACK (on_MNtreeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) MN_chercherbutton, "clicked",
                    G_CALLBACK (on_MN_chercherbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_retourchercher, "clicked",
                    G_CALLBACK (on_MN_retourchercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNcherche, MNcherche, "MNcherche");
  GLADE_HOOKUP_OBJECT (MNcherche, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_entryidchercher, "MN_entryidchercher");
  GLADE_HOOKUP_OBJECT (MNcherche, MNtreeview2, "MNtreeview2");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_verifchercher, "MN_verifchercher");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_chercherbutton, "MN_chercherbutton");
  GLADE_HOOKUP_OBJECT (MNcherche, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (MNcherche, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (MNcherche, image18, "image18");
  GLADE_HOOKUP_OBJECT (MNcherche, label59, "label59");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_resultatcher, "MN_resultatcher");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_textrechercher, "MN_textrechercher");
  GLADE_HOOKUP_OBJECT (MNcherche, MN_retourchercher, "MN_retourchercher");
  GLADE_HOOKUP_OBJECT (MNcherche, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (MNcherche, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (MNcherche, image17, "image17");
  GLADE_HOOKUP_OBJECT (MNcherche, label58, "label58");

  return MNcherche;
}

GtkWidget*
create_MNetagepanne (void)
{
  GtkWidget *MNetagepanne;
  GtkWidget *fixed8;
  GtkWidget *MNtreeview3;
  GtkWidget *MN_affichetage;
  GtkWidget *MN_retourtache2;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label102;

  MNetagepanne = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNetagepanne), _("Etage contenant le panne"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (MNetagepanne), fixed8);

  MNtreeview3 = gtk_tree_view_new ();
  gtk_widget_show (MNtreeview3);
  gtk_fixed_put (GTK_FIXED (fixed8), MNtreeview3, 24, 64);
  gtk_widget_set_size_request (MNtreeview3, 736, 760);

  MN_affichetage = gtk_label_new (_("Les etages contenant des pannes sont :"));
  gtk_widget_show (MN_affichetage);
  gtk_fixed_put (GTK_FIXED (fixed8), MN_affichetage, 16, 16);
  gtk_widget_set_size_request (MN_affichetage, 264, 48);
  gtk_misc_set_alignment (GTK_MISC (MN_affichetage), 0.5, 0.44);

  MN_retourtache2 = gtk_button_new ();
  gtk_widget_show (MN_retourtache2);
  gtk_fixed_put (GTK_FIXED (fixed8), MN_retourtache2, 8, 832);
  gtk_widget_set_size_request (MN_retourtache2, 104, 40);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (MN_retourtache2), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox25), label102, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MNtreeview3, "row_activated",
                    G_CALLBACK (on_MNtreeview3_row_activated),
                    NULL);
  g_signal_connect ((gpointer) MN_retourtache2, "clicked",
                    G_CALLBACK (on_MN_retourtache2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNetagepanne, MNetagepanne, "MNetagepanne");
  GLADE_HOOKUP_OBJECT (MNetagepanne, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (MNetagepanne, MNtreeview3, "MNtreeview3");
  GLADE_HOOKUP_OBJECT (MNetagepanne, MN_affichetage, "MN_affichetage");
  GLADE_HOOKUP_OBJECT (MNetagepanne, MN_retourtache2, "MN_retourtache2");
  GLADE_HOOKUP_OBJECT (MNetagepanne, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (MNetagepanne, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (MNetagepanne, image25, "image25");
  GLADE_HOOKUP_OBJECT (MNetagepanne, label102, "label102");

  return MNetagepanne;
}

GtkWidget*
create_MNauthentification (void)
{
  GtkWidget *MNauthentification;
  GtkWidget *fixed9;
  GtkWidget *MN_authuser;
  GtkWidget *MN_authpass;
  GtkWidget *MN_retourauthen;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image31;
  GtkWidget *label111;
  GtkWidget *MN_login;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *image30;
  GtkWidget *label110;
  GtkWidget *MN_user;
  GtkWidget *MN_Pass;
  GtkWidget *MN_role;
  GtkWidget *MN_autho;
  GtkWidget *MN_roletext;
  GtkWidget *MN_erreur;

  MNauthentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNauthentification), _("Authentification"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (MNauthentification), fixed9);

  MN_authuser = gtk_entry_new ();
  gtk_widget_show (MN_authuser);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_authuser, 48, 144);
  gtk_widget_set_size_request (MN_authuser, 240, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_authuser), 8226);

  MN_authpass = gtk_entry_new ();
  gtk_widget_show (MN_authpass);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_authpass, 48, 232);
  gtk_widget_set_size_request (MN_authpass, 240, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_authpass), 8226);

  MN_retourauthen = gtk_button_new ();
  gtk_widget_show (MN_retourauthen);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_retourauthen, 8, 392);
  gtk_widget_set_size_request (MN_retourauthen, 96, 40);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (MN_retourauthen), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image31 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image31);
  gtk_box_pack_start (GTK_BOX (hbox31), image31, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox31), label111, FALSE, FALSE, 0);

  MN_login = gtk_button_new ();
  gtk_widget_show (MN_login);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_login, 240, 392);
  gtk_widget_set_size_request (MN_login, 104, 37);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (MN_login), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  image30 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox30), image30, FALSE, FALSE, 0);

  label110 = gtk_label_new_with_mnemonic (_(" Login"));
  gtk_widget_show (label110);
  gtk_box_pack_start (GTK_BOX (hbox30), label110, FALSE, FALSE, 0);

  MN_user = gtk_label_new (_("Username :"));
  gtk_widget_show (MN_user);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_user, 0, 96);
  gtk_widget_set_size_request (MN_user, 136, 48);

  MN_Pass = gtk_label_new (_("Password :"));
  gtk_widget_show (MN_Pass);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_Pass, 0, 184);
  gtk_widget_set_size_request (MN_Pass, 136, 40);

  MN_role = gtk_entry_new ();
  gtk_widget_show (MN_role);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_role, 48, 320);
  gtk_widget_set_size_request (MN_role, 240, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (MN_role), 8226);

  MN_autho = gtk_label_new (_("Authentification"));
  gtk_widget_show (MN_autho);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_autho, 48, 8);
  gtk_widget_set_size_request (MN_autho, 264, 48);

  MN_roletext = gtk_label_new (_("Role:"));
  gtk_widget_show (MN_roletext);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_roletext, 16, 288);
  gtk_widget_set_size_request (MN_roletext, 81, 25);

  MN_erreur = gtk_label_new ("");
  gtk_widget_show (MN_erreur);
  gtk_fixed_put (GTK_FIXED (fixed9), MN_erreur, 40, 48);
  gtk_widget_set_size_request (MN_erreur, 273, 48);

  g_signal_connect ((gpointer) MN_retourauthen, "clicked",
                    G_CALLBACK (on_MN_retourauthen_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_login, "clicked",
                    G_CALLBACK (on_MN_login_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNauthentification, MNauthentification, "MNauthentification");
  GLADE_HOOKUP_OBJECT (MNauthentification, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_authuser, "MN_authuser");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_authpass, "MN_authpass");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_retourauthen, "MN_retourauthen");
  GLADE_HOOKUP_OBJECT (MNauthentification, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (MNauthentification, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (MNauthentification, image31, "image31");
  GLADE_HOOKUP_OBJECT (MNauthentification, label111, "label111");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_login, "MN_login");
  GLADE_HOOKUP_OBJECT (MNauthentification, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (MNauthentification, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (MNauthentification, image30, "image30");
  GLADE_HOOKUP_OBJECT (MNauthentification, label110, "label110");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_user, "MN_user");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_Pass, "MN_Pass");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_role, "MN_role");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_autho, "MN_autho");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_roletext, "MN_roletext");
  GLADE_HOOKUP_OBJECT (MNauthentification, MN_erreur, "MN_erreur");

  return MNauthentification;
}

GtkWidget*
create_MNmenu (void)
{
  GtkWidget *MNmenu;
  GtkWidget *fixed10;
  GtkWidget *MN_entryauth;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *image29;
  GtkWidget *label109;
  GtkWidget *MN_entrytdashbord;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label108;

  MNmenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (MNmenu), _("Welcome"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (MNmenu), fixed10);

  MN_entryauth = gtk_button_new ();
  gtk_widget_show (MN_entryauth);
  gtk_fixed_put (GTK_FIXED (fixed10), MN_entryauth, 104, 64);
  gtk_widget_set_size_request (MN_entryauth, 154, 40);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (MN_entryauth), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  image29 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox29), image29, FALSE, FALSE, 0);

  label109 = gtk_label_new_with_mnemonic (_(" Authentification"));
  gtk_widget_show (label109);
  gtk_box_pack_start (GTK_BOX (hbox29), label109, FALSE, FALSE, 0);

  MN_entrytdashbord = gtk_button_new ();
  gtk_widget_show (MN_entrytdashbord);
  gtk_fixed_put (GTK_FIXED (fixed10), MN_entrytdashbord, 104, 128);
  gtk_widget_set_size_request (MN_entrytdashbord, 152, 40);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (MN_entrytdashbord), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_LARGE_TOOLBAR);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label108 = gtk_label_new_with_mnemonic (_(" Dashboard"));
  gtk_widget_show (label108);
  gtk_box_pack_start (GTK_BOX (hbox28), label108, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) MN_entryauth, "clicked",
                    G_CALLBACK (on_MN_entryauth_clicked),
                    NULL);
  g_signal_connect ((gpointer) MN_entrytdashbord, "clicked",
                    G_CALLBACK (on_MN_entrytdashbord_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (MNmenu, MNmenu, "MNmenu");
  GLADE_HOOKUP_OBJECT (MNmenu, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (MNmenu, MN_entryauth, "MN_entryauth");
  GLADE_HOOKUP_OBJECT (MNmenu, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (MNmenu, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (MNmenu, image29, "image29");
  GLADE_HOOKUP_OBJECT (MNmenu, label109, "label109");
  GLADE_HOOKUP_OBJECT (MNmenu, MN_entrytdashbord, "MN_entrytdashbord");
  GLADE_HOOKUP_OBJECT (MNmenu, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (MNmenu, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (MNmenu, image28, "image28");
  GLADE_HOOKUP_OBJECT (MNmenu, label108, "label108");

  return MNmenu;
}

