/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MNaccueil (void);
GtkWidget* create_MNajout (void);
GtkWidget* create_MNmodif (void);
GtkWidget* create_MNsupprime (void);
GtkWidget* create_MNcherche (void);
GtkWidget* create_MNetagepanne (void);
GtkWidget* create_MNauthentification (void);
GtkWidget* create_MNmenu (void);
